## 应用名称
#spring.application.name=gameWeb
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.xiaoze.gameweb.mybatis.entity
## 数据源名称
#spring.datasource.name=defaultDataSource

# 应用服务 WEB 访问端口
server:
  port: 80

spring:
  # 应用名称
  application:
    name: gameWeb
  # 配置数据库连接信息
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/game_web?serverTimezone=UTC
      username: root
      password: 220215
  # 关闭日志图标
  main:
    banner-mode: off
  # 配置跳转页面前后缀
  mvc:
    view:
      prefix:
      suffix:


# mybatis配置信息
mybatis-plus:
  global-config:
    db-config:
      # table-prefix: game_
      id-type: auto
    # 关闭日志图标
    banner: off
